name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          echo "Current Directory: $(pwd)"
          ls -la tests/
          npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release